name: "Publish to Docker"
runs:
  using: "composite"
  steps:
      - name: Setup BuildX
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x	  
