name: use re-usable workflow
on: 
     workflow_dispatch:
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  AppPool: "default"
  Website: "default"
  WebAppDirectory: "C:/CICDDemo"  
jobs:
  deploy-to-web01:  
    runs-on: [self-hosted]
    steps:
    - uses: yasinmagn/CICDDemo/.github/workflows/deploy-stating.yml@main
      with:
        runs-on: "[self-hosted,web01]"
        
    

        
