name: Deploy
on: 
     workflow_dispatch:

jobs:
  build-artifact:  
   uses: yasinmagn/CICDDemo/.github/workflows/deploy-code.yml@master
   with:
    runner-name: windows-latest
  deploy:  
   uses: yasinmagn/CICDDemo/.github/workflows/deploy-code.yml@master
   needs: build-artifact
   with:
    runner-name: "['self-hosted','web01-server']"  

   
