name: Reusable workflow example

on:
  workflow_call:
    inputs:
      runner-name:
        required: false
        type: string
    secrets:
      token:
        required: false
env:
  AppPool: "DefaultAppPool"
  Website: " 'Default Web Site' "

jobs:
  build:
    runs-on: ${{ fromJson(inputs.runner-name) }}
    steps:
    - name: echo data
      run: |
           echo ${{env.AppPool}}
            echo ${{env.Website}}
    - uses: actions/checkout@v3


    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
