name: Reusable workflow example

on:
  workflow_call:
    inputs:
      runner-name:
        required: false
        type: string
    secrets:
      token:
        required: false
env:
 path: '"Literature Review/Review.tex"'   

jobs:
  build:
    runs-on: ${{ fromJson(inputs.runner-name) }}
    steps:
    - name: echo data
      run: |
           echo ${path}
           ${LATEX} ${path}
    - uses: actions/checkout@v3


    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
