name: Reusable workflow example

on:
  workflow_call:
    inputs:
      runner-name:
        required: false
        type: string
    secrets:
      token:
        required: false
env:
  AppPool: "DefaultAppPool"
  Website: "Default Web Site"

jobs:
  build:
    runs-on: ${{ fromJson(inputs.runner-name) }}
    steps:
    - name: echo data
      run: |
           echo ${{env.AppPool}}
            echo ""${{env.Website}}""
