name: Reusable workflow example

on:
  workflow_call:
    inputs:
      target-machine:
        required: true
        type: string
      runner-name:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  triage:
    runs-on: ${{inputs.runs-on}}
    steps:
    - uses: actions/labeler@v4
