name: Reusable workflow example

on:
  workflow_call:
    inputs:
      target-machine:
        required: true
        type: string
      runner-name:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  triage:
    runs-on: ${{inputs.runs-on}}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
